language: java
notifications:
  slack:
    secure: zEpFwp7e5t0dnvd/BX7gFctTB7ZrZ8gFDPMy/fEAP2jaVr2QZ9QMOBaCiHCqeROUQBD6yGG44KmQ9y7YXVIRD2gVBSk8wPVBWyZy7R3ZJZSXzQc/jCWHysOXAc+7Iik5U/8ZBZDN6Nk07g6hrr0Y1b4xhB9j4mQ3g1pL1DzjQycVP1YMUbauslZkPd1vWGBaLVeehge1XeTgoxQrQKFD+MGzaWzUYQbrmXYV5kLslqC4dOotxuUZFPlZOcgg8+l5/RNNCcTnE/AHTn7L0YeZSILdS+0AI3iAzmyyjrGWB5jux+pE4mxpfLSiG4NMYp/nRjsfKSzEHDZq9C0n4yRzgwDYLRBT4jDpPVKLRg/i4pPXKOpUcTUYsh3jwiNZOmg+htkYTMVR7ryVn/b2KMUu8IRz5NtBYwZKLajfcS8SLYscwvxp1OrwGIFScUN0wGqN+My+zqDwtKZ3xNZRU8yzulo0u/HUykm1K91laiobSFA08KjFBcarBr700z8QDdtRloLokxVVZgc8nWD1aKSoLlMbQIhN0IvXgFiN42eloYM/AvSkr3llsFff+7OiZUE2aWEY26RQj6pBC2pij+6oDceKsB1rXaSBueUG7rqJW9DR1Sw5yNtDjbALYtq6LPg47JWxDVfsg/FrySswGtWmLVQ4azqftktd4rU4RSFd7m0=
deploy:
  provider: releases
  api_key:
    secure: vZf2jrAlfpDxbLAygjpwYZkq7PIoSu1q0g78C5QJsevO2uH49mFS/7c4bpD/I72/S5Pv8hTJE/KUm6ziuq3PAvYXWrR81u/QgNgOTbXS25SyCG11ulq14wORC4r82TLHT3kcqF1kwsMcPv18JsAfqMZp0smL/PZwc42OG+X634lAmqkwu1Dy8QUD0bRHQz/htRYes6mGSXBo2axMcKwrua7IZquKds8a4xJJLlu1iTg7MlpMhgkJCYN86eFGPeyzwKF+RuXlNVkONI1EMAgcVpS5Yex9d5FbUE8YdS/hxme6sdGNdAScdpOpWuImybewZrjGZ/8Le14ItGbbpeXDypXmPLVtRo6Xa550q5VBMdeknT2OYecG4vZR2Tn4s8uG3C85NKzsITgisqBVWZxQrgEG6Ed3CjmZkYRlCnqv3ezCzw/U09GmdgjbJ+TIY/4Y9wbn1u6tieFBS8kTJYEuuyh4amhATU+7NrsaBOeoEWc83dSxbHabpuRAq+BNoydHEGu9VPLfpgC02mm/3jd4K8phEhoFAxreAMm+mKYh3otxCTLioq5FYxjv1k5h7EK2u3SvgnAQAw+StF4KAaFA9n1rvo2SFPNNakQP1ougUa8YLYjeHLq0sN2HRrO4qH8709EPG+bIbXo5iIERJADM4MjQcHEHEIOXhf+US8vDk3g=
  file: build/distributions/*
  skip_cleanup: true
  edge: true
  on:
    all_branches: true
    tags: true      
    repo: xebialabs-community/xld-jython-dictionary-plugin